Add analysis of unsafe code in dependencies through cargo geiger
diem/whackadep pull request #72
Opened 2021-06-21 13:09 UTC by nasifimtiazohi

## Changes made
Add processing of cargo geiger report for unsafe code

## Improvement TODO 
1. As Cargo geiger cannot run over a virtual manifest and need to run over a package.toml, our code runs cargo geiger over all member packages making it a very expensive and time consuming process.

2021-06-21 16:59 UTC, xvschneider submitted a review, later dismissed
Looks good!

2021-06-21 22:48 UTC, metajack requested changes
Looks good although I think we can hide the cache from caller code a bit and make it easier to get reports instead of having to test keys and stuff everywhere the reports might get used.

2021-06-21 22:48 UTC, metajack commented on analysis/src/code.rs
> +        let cache = self.geiger_cache.borrow();
Maybe there should be a `get_cargo_geiger_report` that grabs one from the cache based on the key? That would hide the cache a bit from the other code.

2021-06-21 23:04 UTC, metajack commented on analysis/src/code.rs
> +        let cache = self.geiger_cache.borrow();
Probably it would return `Option<CargoGeigerReport>`.

2021-06-22 02:00 UTC, metajack approved these changes

2021-06-22 02:18 UTC, merged